version: '3.9'
services:

  db:
    image: postgres:15.2-alpine
    restart: always
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: ${DB_NAME}
    networks:
      - pgadmin-postgres

  pgAdmin:
    depends_on:
      - db
    image: dpage/pgadmin4:6.17
    restart: always
    volumes:
      - pg-admin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
    ports:
      - ${PG_ADMIN_PORT}:80
    container_name: ${PG_ADMIN_CONTAINER_NAME}
    networks:
      - pgadmin-postgres

volumes:
  pg-admin:
    name: pg-admin
    external: false
  postgres-db:
    name: postgres-db
    external: false

networks:
  pgadmin-postgres:
    name: pgadmin-postgres
    driver: bridge
